### PR TITLE
Redirect back to your website, on contacting you

### PR DESCRIPTION
**Pull request by ir-g**

### CODE REVIEW

**Comment by ir-g** [comment]
@ChilliByte Thanks! Isn't Hacktoberfest awesome?

**Comment by ChilliByte** [comment]
You're welcome! It's amazing! Especially with all the ultra technical, meaningful code we've been writing to aid each other!

**Comment by ir-g** [comment]
IKR. :stuck_out_tongue:

Also, Github supports [emoji](http://www.emoji-cheat-sheet.com/)

**Comment by ChilliByte** [comment]
:+1:

**Pull request merged**
